language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev
before_script:
  - dart pub run chrome_travis:init
  - source $(dart pub run chrome_travis:env_rc -v)
script:
 - dart ./tool/travis.dart