# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Qwen3B
    provider: llama.cpp
    model: Qwen/Qwen2.5-Coder-3B-Instruct-GGUF:Q6_K
    apiBase: http://localhost:8080
# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
